version: "3.9"

services:
  database1:
    image: mysql:8.0
    container_name: mysql1
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: sql11677927
      MYSQL_USER: sql11677927
      MYSQL_PASSWORD: bQWR76Jty8
      MYSQL_ROOT_PASSWORD: pass

    networks:
      - internal

  database2:
    image: mysql:8.0
    container_name: mysql2
    ports:
      - "3367:3306"
    environment:
      MYSQL_DATABASE: sql11681873
      MYSQL_USER: sql11681873
      MYSQL_PASSWORD: YNwbiupSuY
      MYSQL_ROOT_PASSWORD: pass

    networks:
      - internal

  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
    networks:
      - internal

  auth-service:
    image: auth-service
    ports:
      - "8081:8081"

  discovery-server:
    image: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  frontend:
    image: frontend-service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  gateway:
    image: gateway-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  payment:
    image: payment-service
    build:
      context: ./payment
      dockerfile: Dockerfile

    ports:
      - "8083:8083"

  app:
    container_name: product
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - database1
      - database2
    volumes:
      - ./:/app/app
    links:
      - database1
      - database2
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11677927
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
  

networks:
  internal:
    name: internal